spring:
  profiles: single
  application:
    name: eureka-service
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    locale: zh_CN
    time-zone: GMT+8
server:
  port: 8761
eureka:
  instance:
    appname: ${spring.application.name}
    hostname: localhost
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: false
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 5000
---
spring:
  profiles: cluster
  application:
    name: eureka-service
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    locale: zh_CN
    time-zone: GMT+8
server:
  port: ${serverPort}
eureka:
  instance:
    appname: ${spring.application.name}
    hostname: ${hostName}
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: false
  client:
    serviceUrl:
      defaultZone: ${eurekaServerUrl}
  server:
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 5000
