spring:
  application:
    name: demo-eureka
  profiles: single
server:
  port: ${serverPort}
eureka:
  instance:
    appname: ${spring.application.name}
    hostname: ${hostName}
    instanceId: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
---
spring:
  application:
    name: demo-eureka
  profiles: multiple
server:
  port: ${serverPort}
eureka:
  instance:
    appname: ${spring.application.name}
    hostname: ${hostName}
    instanceId: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    serviceUrl:
      defaultZone: ${eurekaServerUrl}
